

// // // Dynamic Tab Content Component with Author Section
// // "use client";
// // import { useState } from "react";

// // // Import your data from utils folder
// // // import tabsData from "@/utils/tabsData.json";

// // // Example data structure - replace this with your actual import
// // const tabsData = {
// //   "Proprietorship": {
// //     title: "Proprietorship Registration in India",
// //     description: "Setting up a sole proprietorship business in India is one of the simplest and most cost-effective ways to start your entrepreneurial journey. This business structure is ideal for individual entrepreneurs who want complete control over their business operations without the complexities of forming a company or partnership. A proprietorship offers minimal compliance requirements, making it the preferred choice for small businesses, freelancers, and solo entrepreneurs.",
// //     introduction: "At IndiaFilings, we offer a comprehensive and cost-effective service to register your proprietorship business in India. We handle all legal formalities for proprietorship registration, ensuring strict compliance with government regulations and providing you with expert guidance throughout the entire process.",
// //     sections: [
// //       {
// //         heading: "What is a Sole Proprietorship?",
// //         content: "In India, a sole proprietorship is a business structure owned and operated by a single individual with no distinction between the owner and the business entity. It is the most straightforward form of business organization and requires minimal regulatory compliance. The proprietor has unlimited liability, meaning personal assets may be used to settle business debts. This structure is particularly suitable for small-scale businesses, freelancers, consultants, and service providers who want to test their business idea with minimal investment and formalities.",
// //         points: [
// //           "Single Ownership and Control: The proprietor has complete authority over all business decisions, operations, and profits. There is no need to consult partners or shareholders, allowing for quick decision-making and operational flexibility.",
// //           "No Separate Legal Entity: Unlike companies or LLPs, a proprietorship does not have a separate legal identity from its owner. The business and the proprietor are considered one and the same under Indian law.",
// //           "Unlimited Personal Liability: The proprietor is personally responsible for all debts and obligations of the business. In case of business failure or legal disputes, personal assets may be at risk to satisfy business liabilities.",
// //           "Minimal Compliance Requirements: Proprietorships face significantly lower regulatory burdens compared to companies. There are no mandatory annual filings with the Registrar of Companies, making it easier and more affordable to maintain.",
// //           "Easy Formation and Dissolution: Starting a proprietorship requires minimal documentation and can be set up quickly. Similarly, closing the business is straightforward without complex legal procedures or government approvals."
// //         ]
// //       },
// //       {
// //         heading: "Key Features of Proprietorship",
// //         content: "A sole proprietorship comes with several distinctive characteristics that make it an attractive option for individual entrepreneurs and small business owners in India.",
// //         points: [
// //           "Complete Management Control: The proprietor enjoys absolute control over all aspects of the business, including strategic planning, daily operations, financial management, and growth decisions. This autonomy enables rapid response to market changes and customer needs.",
// //           "Low Cost of Establishment: Starting a proprietorship involves minimal investment in registration fees and documentation. Unlike companies that require paid-up capital and extensive incorporation costs, proprietorships can be established with basic registrations like GST and professional tax.",
// //           "Direct Ownership of All Profits: All income generated by the business belongs entirely to the proprietor. There is no requirement to share profits with partners or shareholders, maximizing the financial benefits of successful business operations.",
// //           "Minimal Legal Formalities: Proprietorships are not required to comply with the Companies Act, 2013, or maintain statutory registers. There are no mandatory board meetings, annual general meetings, or complex financial reporting requirements.",
// //           "Taxation Under Individual Income Tax: The business income is taxed as part of the proprietor's personal income under applicable income tax slabs. This allows the proprietor to claim various deductions and exemptions available to individuals, potentially reducing overall tax liability."
// //         ]
// //       },
// //       {
// //         heading: "Required Documents for Proprietorship Registration",
// //         content: "While proprietorship registration is relatively simple, certain basic documents are required to establish the business identity and comply with various regulatory requirements.",
// //         points: [
// //           "PAN Card of the Proprietor: A valid Permanent Account Number (PAN) issued by the Income Tax Department is mandatory for all business registrations. It serves as the primary identification for tax purposes and financial transactions.",
// //           "Aadhaar Card for Identity Verification: The proprietor's Aadhaar card is required for identity verification and linking with various business registrations. It may also be needed for opening a business bank account and obtaining government licenses.",
// //           "Proof of Business Address: Documents establishing the business premises are essential for registration. Acceptable proofs include rental agreements with rent receipts, property ownership documents, utility bills (electricity or water), or a No Objection Certificate (NOC) from the property owner.",
// //           "Current Bank Account Details: A bank account in the name of the proprietorship is necessary for conducting business transactions. Banks typically require business registration documents and address proof to open a current account.",
// //           "Business Registration Certificates: Depending on the nature of business, you may need to obtain registrations such as GST registration for businesses exceeding the threshold turnover, Shops and Establishment License from the local municipal authority, or MSME/Udyam Registration for availing benefits under government schemes."
// //         ]
// //       },
// //       {
// //         heading: "Benefits of Proprietorship Registration",
// //         content: "Choosing a proprietorship structure offers numerous advantages that make it ideal for solo entrepreneurs and small business owners starting their ventures.",
// //         points: [
// //           "Extremely Low Setup and Maintenance Costs: Proprietorships require minimal capital investment to start and have negligible ongoing compliance costs. There are no annual filing fees with the Registrar of Companies, no audit requirements for smaller businesses, and reduced accounting expenses.",
// //           "Complete Autonomy in Business Management: The proprietor has absolute freedom to make all business decisions without needing approval from partners, shareholders, or board members. This independence allows for quick adaptation to market opportunities and challenges.",
// //           "Simplified Accounting and Record-Keeping: Unlike companies that must maintain extensive statutory registers and follow strict accounting standards, proprietorships can maintain basic books of accounts. Small businesses with turnover below specified limits can opt for presumptive taxation schemes.",
// //           "Easy Business Closure Process: Dissolving a proprietorship is straightforward and does not require lengthy legal procedures. The proprietor can simply cease operations, close the business bank account, and cancel relevant registrations without going through formal liquidation processes.",
// //           "Tax Benefits Under Presumptive Taxation: Proprietors engaged in specified businesses can opt for presumptive taxation schemes under Sections 44AD, 44ADA, or 44AE of the Income Tax Act, which significantly simplifies tax compliance and reduces the need for detailed financial statements and tax audits."
// //         ]
// //       }
// //     ],
// //     author: {
// //       name: "SANTOSH KUMARI M",
// //       role: "Business Advisor",
// //       image: "/author-avatar.jpg",
// //       updatedDate: "Oct 27, 2025"
// //     }
// //   },
// //   "Partnership": {
// //     title: "Partnership Firm Registration in India",
// //     description: "A partnership firm is a popular business structure where two or more individuals come together to carry on a business with a view to making profits. This arrangement allows entrepreneurs to pool their resources, skills, and expertise while sharing the risks and rewards of business operations. Partnership firms are governed by the Indian Partnership Act, 1932, and offer flexibility in management and operations.",
// //     introduction: "At IndiaFilings, we provide comprehensive partnership firm registration services to help entrepreneurs establish their business partnerships efficiently. Our expert team handles all documentation, legal formalities, and compliance requirements, ensuring your partnership firm is registered smoothly and in accordance with applicable laws.",
// //     sections: [
// //       {
// //         heading: "What is a Partnership Firm?",
// //         content: "A partnership firm is a business arrangement where two or more persons agree to share the profits and losses of a business carried on by all or any of them acting for all. The relationship between partners is based on mutual trust and agreement, making it essential to have a well-drafted partnership deed that clearly outlines the rights, duties, and obligations of each partner.",
// //         points: [
// //           "Minimum Two Partners Required: A partnership must have at least two partners to be formed. The maximum number of partners is limited to 50 under the Companies Act, 2013. Partners can be individuals or entities, and they collectively manage the business operations.",
// //           "Governed by Partnership Act, 1932: Partnership firms in India operate under the provisions of the Indian Partnership Act, 1932, which defines the legal framework for partnership relationships, rights of partners, registration procedures, and dissolution mechanisms.",
// //           "Partnership Deed is Essential: A partnership deed is a written agreement that contains all terms and conditions of the partnership, including profit-sharing ratios, capital contributions, roles and responsibilities, dispute resolution mechanisms, and procedures for admission or retirement of partners.",
// //           "Unlimited Liability for Partners: Partners in a general partnership have unlimited liability, meaning their personal assets can be used to satisfy business debts. Each partner is jointly and severally liable for the acts of other partners performed in the ordinary course of business.",
// //           "Mutual Agency Relationship: Every partner is an agent of the firm and other partners. Actions taken by one partner in the ordinary course of business bind the firm and all other partners, making trust and transparency crucial in partnership arrangements."
// //         ]
// //       },
// //       {
// //         heading: "Key Features of Partnership Firm",
// //         content: "Partnership firms possess several distinctive characteristics that make them suitable for businesses where multiple individuals want to combine their skills, resources, and expertise.",
// //         points: [
// //           "Shared Financial Burden and Resources: Partners contribute capital according to the partnership agreement, reducing the individual financial burden. This pooling of resources enables the business to access more capital than would be available to a single proprietor, facilitating business growth and expansion.",
// //           "Flexibility in Management and Operations: Partnership firms enjoy considerable operational flexibility. Partners can define their roles, responsibilities, and decision-making processes according to their agreement. Unlike companies, partnerships are not bound by rigid corporate governance requirements.",
// //           "Combined Skills and Expertise: Partnerships bring together individuals with diverse skills, knowledge, and business acumen. This collective expertise enhances problem-solving capabilities, strategic planning, and overall business performance, allowing the firm to handle complex challenges more effectively.",
// //           "Ease of Formation: Forming a partnership is relatively straightforward and involves minimal regulatory compliance. While registration with the Registrar of Firms is optional, it provides several legal advantages and is highly recommended for protecting partners' interests.",
// //           "Tax Advantages for Partners: Partnership firms are taxed as separate entities at a flat rate of 30% plus applicable surcharge and cess. Additionally, partners can claim salary and interest on capital as deductible expenses, potentially reducing the overall tax burden on the firm."
// //         ]
// //       },
// //       {
// //         heading: "Required Documents for Partnership Registration",
// //         content: "To register a partnership firm with the Registrar of Firms, certain documents must be prepared and submitted along with the application.",
// //         points: [
// //           "Partnership Deed on Appropriate Stamp Paper: The partnership deed is the foundational document that outlines all terms of the partnership. It must be executed on non-judicial stamp paper of appropriate value as per the state stamp duty regulations. The deed should clearly specify the firm name, business nature, capital contributions, profit-sharing ratios, and other essential terms.",
// //           "PAN Card and Aadhaar Card of All Partners: Valid PAN cards of all partners are mandatory for obtaining the firm's PAN. Aadhaar cards are required for identity verification and may be needed for various registrations and licenses. Both documents should be self-attested copies.",
// //           "Address Proof of All Partners: Partners must provide address proof such as passport, voter ID card, driver's license, or recent utility bills. These documents establish the residential address of each partner and are necessary for maintaining the firm's records.",
// //           "Proof of Principal Place of Business: Documentation proving the business premises is essential. This can include a rental agreement with rent receipts and NOC from the landlord, property ownership documents, or utility bills in the firm's name. The address proof should not be older than two months.",
// //           "Passport Size Photographs: Recent passport-size photographs of all partners are required for the registration application and various other registrations. These photographs should meet standard specifications and be taken against a light-colored background."
// //         ]
// //       },
// //       {
// //         heading: "Benefits of Partnership Firm",
// //         content: "Choosing a partnership structure offers multiple advantages for entrepreneurs who want to collaborate and build a business together.",
// //         points: [
// //           "Easy to Form and Dissolve: Partnership firms can be formed with minimal formalities and documentation. Similarly, dissolution is relatively straightforward compared to companies, though it requires settlement of accounts, payment of liabilities, and distribution of remaining assets among partners.",
// //           "Shared Risks and Responsibilities: Business risks are distributed among partners according to their profit-sharing ratios or as agreed in the partnership deed. This risk-sharing mechanism reduces individual exposure to business failures and provides emotional and financial support during challenging times.",
// //           "Greater Access to Capital and Credit: With multiple partners contributing capital, partnership firms have access to more funds than sole proprietorships. Additionally, the combined creditworthiness of partners may help secure better financing terms from banks and financial institutions.",
// //           "Flexibility in Business Operations: Partnerships are not subject to extensive regulatory requirements like companies. Partners have the freedom to modify their business structure, profit-sharing arrangements, and operational processes by mutual consent without needing government approvals.",
// //           "Tax Benefits and Deductions: Partnership firms can claim various deductions including interest on partner capital, remuneration to working partners (subject to limits), and other business expenses. These deductions help reduce the taxable income of the firm and overall tax liability."
// //         ]
// //       }
// //     ],
// //     author: {
// //       name: "SANTOSH KUMARI M",
// //       role: "Business Advisor",
// //       image: "/author-avatar.jpg",
// //       updatedDate: "Oct 27, 2025"
// //     }
// //   }
// // };

// // interface DynamicTabContentProps {
// //   tabName: string;
// // }

// // export default function DynamicTabContent({ tabName }: DynamicTabContentProps) {
// //   const data = tabsData[tabName as keyof typeof tabsData];

// //   if (!data) {
// //     return (
// //       <div className="bg-red-50 border border-red-200 rounded-lg p-6 text-center">
// //         <p className="text-red-600 font-medium">
// //           No data found for "{tabName}". Please check the tab name.
// //         </p>
// //       </div>
// //     );
// //   }

// //   return (
// //     <div className="bg-white rounded-lg shadow-sm border border-gray-200 overflow-hidden max-w-5xl mx-auto">
// //       {/* Author Section */}
// //       <div className="bg-gray-50 px-8 py-6 border-b border-gray-200">
// //         <div className="flex items-center justify-between">
// //           <div className="flex items-center gap-4">
// //             <div className="w-14 h-14 bg-gradient-to-br from-blue-500 to-purple-600 rounded-full flex items-center justify-center text-white font-bold text-xl">
// //               {data.author.name.split(' ').map(n => n[0]).join('')}
// //             </div>
// //             <div>
// //               <h3 className="text-base font-bold text-gray-900">
// //                 {data.author.name}
// //               </h3>
// //               <p className="text-sm text-gray-600">{data.author.role}</p>
// //             </div>
// //           </div>
// //           <div className="text-right">
// //             <p className="text-sm text-gray-500">Updated on:</p>
// //             <p className="text-sm font-semibold text-gray-900">{data.author.updatedDate}</p>
// //           </div>
// //         </div>
// //       </div>

// //       {/* Main Content */}
// //       <div className="px-8 py-10 space-y-8">
// //         {/* Title */}
// //         <h1 className="text-3xl md:text-4xl font-bold text-gray-900 leading-tight">
// //           {data.title}
// //         </h1>

// //         {/* Description */}
// //         <p className="text-gray-700 text-base leading-relaxed">
// //           {data.description}
// //         </p>

// //         {/* Introduction */}
// //         <p className="text-gray-700 text-base leading-relaxed">
// //           {data.introduction}
// //         </p>

// //         {/* Sections */}
// //         {data.sections.map((section, index) => (
// //           <div key={index} className="space-y-5">
// //             <h2 className="text-2xl font-bold text-gray-900 mt-8">
// //               {section.heading}
// //             </h2>
            
// //             <p className="text-gray-700 text-base leading-relaxed">
// //               {section.content}
// //             </p>

// //             <ul className="space-y-4 mt-4">
// //               {section.points.map((point, pointIndex) => {
// //                 const [title, ...description] = point.split(':');
// //                 return (
// //                   <li key={pointIndex} className="flex items-start gap-3">
// //                     <svg
// //                       className="w-5 h-5 text-blue-600 flex-shrink-0 mt-1"
// //                       fill="currentColor"
// //                       viewBox="0 0 20 20"
// //                     >
// //                       <path
// //                         fillRule="evenodd"
// //                         d="M16.707 5.293a1 1 0 010 1.414l-8 8a1 1 0 01-1.414 0l-4-4a1 1 0 011.414-1.414L8 12.586l7.293-7.293a1 1 0 011.414 0z"
// //                         clipRule="evenodd"
// //                       />
// //                     </svg>
// //                     <div className="flex-1">
// //                       <span className="font-semibold text-gray-900">{title}:</span>
// //                       <span className="text-gray-700"> {description.join(':')}</span>
// //                     </div>
// //                   </li>
// //                 );
// //               })}
// //             </ul>
// //           </div>
// //         ))}
// //       </div>
// //     </div>
// //   );
// // }

// // // Example Usage Component
// // export function TabsExample() {
// //   const [activeTab, setActiveTab] = useState("Proprietorship");

// //   const tabs = [
// //     "Proprietorship",
// //     "Partnership",
// //     "One Person Company",
// //     "Limited Liability Partnership",
// //     "Private Limited Company",
// //     "Section 8 Company",
// //     "Trust Registration",
// //     "Public Limited Company",
// //     "Producer Company",
// //     "Indian Subsidiary"
// //   ];

// //   return (
// //     <div className="max-w-7xl mx-auto p-6 space-y-6">
// //       {/* Tabs Navigation */}
// //       <div className="bg-white rounded-xl shadow-md border border-gray-200 p-4">
// //         <div className="grid grid-cols-2 md:grid-cols-5 gap-3">
// //           {tabs.map((tab) => (
// //             <button
// //               key={tab}
// //               onClick={() => setActiveTab(tab)}
// //               className={`px-4 py-3 rounded-lg text-sm font-medium transition-all ${
// //                 activeTab === tab
// //                   ? "bg-blue-600 text-white shadow-md"
// //                   : "bg-gray-50 text-gray-700 hover:bg-gray-100 border border-gray-200"
// //               }`}
// //             >
// //               {tab}
// //             </button>
// //           ))}
// //         </div>
// //       </div>

// //       {/* Dynamic Content */}
// //       <DynamicTabContent tabName={activeTab} />
// //     </div>
// //   );
// // }



















// // Dynamic Tab Content Component with Author Section
// "use client";
// import { useState } from "react";

// // Import your data from utils folder
// // import tabsData from "@/utils/tabsData.json";

// // Example data structure - replace this with your actual import
// const tabsData = {
//   "Proprietorship": {
//     title: "Proprietorship Registration in India",
//     description: "Setting up a sole proprietorship business in India is one of the simplest and most cost-effective ways to start your entrepreneurial journey. This business structure is ideal for individual entrepreneurs who want complete control over their business operations without the complexities of forming a company or partnership. A proprietorship offers minimal compliance requirements, making it the preferred choice for small businesses, freelancers, and solo entrepreneurs.",
//     introduction: "At IndiaFilings, we offer a comprehensive and cost-effective service to register your proprietorship business in India. We handle all legal formalities for proprietorship registration, ensuring strict compliance with government regulations and providing you with expert guidance throughout the entire process.",
//     sections: [
//       {
//         heading: "What is a Sole Proprietorship?",
//         content: "In India, a sole proprietorship is a business structure owned and operated by a single individual with no distinction between the owner and the business entity. It is the most straightforward form of business organization and requires minimal regulatory compliance. The proprietor has unlimited liability, meaning personal assets may be used to settle business debts. This structure is particularly suitable for small-scale businesses, freelancers, consultants, and service providers who want to test their business idea with minimal investment and formalities.",
//         points: [
//           "Single Ownership and Control: The proprietor has complete authority over all business decisions, operations, and profits. There is no need to consult partners or shareholders, allowing for quick decision-making and operational flexibility.",
//           "No Separate Legal Entity: Unlike companies or LLPs, a proprietorship does not have a separate legal identity from its owner. The business and the proprietor are considered one and the same under Indian law.",
//           "Unlimited Personal Liability: The proprietor is personally responsible for all debts and obligations of the business. In case of business failure or legal disputes, personal assets may be at risk to satisfy business liabilities.",
//           "Minimal Compliance Requirements: Proprietorships face significantly lower regulatory burdens compared to companies. There are no mandatory annual filings with the Registrar of Companies, making it easier and more affordable to maintain.",
//           "Easy Formation and Dissolution: Starting a proprietorship requires minimal documentation and can be set up quickly. Similarly, closing the business is straightforward without complex legal procedures or government approvals."
//         ]
//       },
//       {
//         heading: "Key Features of Proprietorship",
//         content: "A sole proprietorship comes with several distinctive characteristics that make it an attractive option for individual entrepreneurs and small business owners in India.",
//         points: [
//           "Complete Management Control: The proprietor enjoys absolute control over all aspects of the business, including strategic planning, daily operations, financial management, and growth decisions. This autonomy enables rapid response to market changes and customer needs.",
//           "Low Cost of Establishment: Starting a proprietorship involves minimal investment in registration fees and documentation. Unlike companies that require paid-up capital and extensive incorporation costs, proprietorships can be established with basic registrations like GST and professional tax.",
//           "Direct Ownership of All Profits: All income generated by the business belongs entirely to the proprietor. There is no requirement to share profits with partners or shareholders, maximizing the financial benefits of successful business operations.",
//           "Minimal Legal Formalities: Proprietorships are not required to comply with the Companies Act, 2013, or maintain statutory registers. There are no mandatory board meetings, annual general meetings, or complex financial reporting requirements.",
//           "Taxation Under Individual Income Tax: The business income is taxed as part of the proprietor's personal income under applicable income tax slabs. This allows the proprietor to claim various deductions and exemptions available to individuals, potentially reducing overall tax liability."
//         ]
//       },
//       {
//         heading: "Required Documents for Proprietorship Registration",
//         content: "While proprietorship registration is relatively simple, certain basic documents are required to establish the business identity and comply with various regulatory requirements.",
//         points: [
//           "PAN Card of the Proprietor: A valid Permanent Account Number (PAN) issued by the Income Tax Department is mandatory for all business registrations. It serves as the primary identification for tax purposes and financial transactions.",
//           "Aadhaar Card for Identity Verification: The proprietor's Aadhaar card is required for identity verification and linking with various business registrations. It may also be needed for opening a business bank account and obtaining government licenses.",
//           "Proof of Business Address: Documents establishing the business premises are essential for registration. Acceptable proofs include rental agreements with rent receipts, property ownership documents, utility bills (electricity or water), or a No Objection Certificate (NOC) from the property owner.",
//           "Current Bank Account Details: A bank account in the name of the proprietorship is necessary for conducting business transactions. Banks typically require business registration documents and address proof to open a current account.",
//           "Business Registration Certificates: Depending on the nature of business, you may need to obtain registrations such as GST registration for businesses exceeding the threshold turnover, Shops and Establishment License from the local municipal authority, or MSME/Udyam Registration for availing benefits under government schemes."
//         ]
//       },
//       {
//         heading: "Benefits of Proprietorship Registration",
//         content: "Choosing a proprietorship structure offers numerous advantages that make it ideal for solo entrepreneurs and small business owners starting their ventures.",
//         points: [
//           "Extremely Low Setup and Maintenance Costs: Proprietorships require minimal capital investment to start and have negligible ongoing compliance costs. There are no annual filing fees with the Registrar of Companies, no audit requirements for smaller businesses, and reduced accounting expenses.",
//           "Complete Autonomy in Business Management: The proprietor has absolute freedom to make all business decisions without needing approval from partners, shareholders, or board members. This independence allows for quick adaptation to market opportunities and challenges.",
//           "Simplified Accounting and Record-Keeping: Unlike companies that must maintain extensive statutory registers and follow strict accounting standards, proprietorships can maintain basic books of accounts. Small businesses with turnover below specified limits can opt for presumptive taxation schemes.",
//           "Easy Business Closure Process: Dissolving a proprietorship is straightforward and does not require lengthy legal procedures. The proprietor can simply cease operations, close the business bank account, and cancel relevant registrations without going through formal liquidation processes.",
//           "Tax Benefits Under Presumptive Taxation: Proprietors engaged in specified businesses can opt for presumptive taxation schemes under Sections 44AD, 44ADA, or 44AE of the Income Tax Act, which significantly simplifies tax compliance and reduces the need for detailed financial statements and tax audits."
//         ]
//       }
//     ],
//     author: {
//       name: "SANTOSH KUMARI M",
//       role: "Business Advisor",
//       image: "/author-avatar.jpg",
//       updatedDate: "Oct 27, 2025"
//     }
//   },
//   "Partnership": {
//     title: "Partnership Firm Registration in India",
//     description: "A partnership firm is a popular business structure where two or more individuals come together to carry on a business with a view to making profits. This arrangement allows entrepreneurs to pool their resources, skills, and expertise while sharing the risks and rewards of business operations. Partnership firms are governed by the Indian Partnership Act, 1932, and offer flexibility in management and operations.",
//     introduction: "At IndiaFilings, we provide comprehensive partnership firm registration services to help entrepreneurs establish their business partnerships efficiently. Our expert team handles all documentation, legal formalities, and compliance requirements, ensuring your partnership firm is registered smoothly and in accordance with applicable laws.",
//     sections: [
//       {
//         heading: "What is a Partnership Firm?",
//         content: "A partnership firm is a business arrangement where two or more persons agree to share the profits and losses of a business carried on by all or any of them acting for all. The relationship between partners is based on mutual trust and agreement, making it essential to have a well-drafted partnership deed that clearly outlines the rights, duties, and obligations of each partner.",
//         points: [
//           "Minimum Two Partners Required: A partnership must have at least two partners to be formed. The maximum number of partners is limited to 50 under the Companies Act, 2013. Partners can be individuals or entities, and they collectively manage the business operations.",
//           "Governed by Partnership Act, 1932: Partnership firms in India operate under the provisions of the Indian Partnership Act, 1932, which defines the legal framework for partnership relationships, rights of partners, registration procedures, and dissolution mechanisms.",
//           "Partnership Deed is Essential: A partnership deed is a written agreement that contains all terms and conditions of the partnership, including profit-sharing ratios, capital contributions, roles and responsibilities, dispute resolution mechanisms, and procedures for admission or retirement of partners.",
//           "Unlimited Liability for Partners: Partners in a general partnership have unlimited liability, meaning their personal assets can be used to satisfy business debts. Each partner is jointly and severally liable for the acts of other partners performed in the ordinary course of business.",
//           "Mutual Agency Relationship: Every partner is an agent of the firm and other partners. Actions taken by one partner in the ordinary course of business bind the firm and all other partners, making trust and transparency crucial in partnership arrangements."
//         ]
//       },
//       {
//         heading: "Key Features of Partnership Firm",
//         content: "Partnership firms possess several distinctive characteristics that make them suitable for businesses where multiple individuals want to combine their skills, resources, and expertise.",
//         points: [
//           "Shared Financial Burden and Resources: Partners contribute capital according to the partnership agreement, reducing the individual financial burden. This pooling of resources enables the business to access more capital than would be available to a single proprietor, facilitating business growth and expansion.",
//           "Flexibility in Management and Operations: Partnership firms enjoy considerable operational flexibility. Partners can define their roles, responsibilities, and decision-making processes according to their agreement. Unlike companies, partnerships are not bound by rigid corporate governance requirements.",
//           "Combined Skills and Expertise: Partnerships bring together individuals with diverse skills, knowledge, and business acumen. This collective expertise enhances problem-solving capabilities, strategic planning, and overall business performance, allowing the firm to handle complex challenges more effectively.",
//           "Ease of Formation: Forming a partnership is relatively straightforward and involves minimal regulatory compliance. While registration with the Registrar of Firms is optional, it provides several legal advantages and is highly recommended for protecting partners' interests.",
//           "Tax Advantages for Partners: Partnership firms are taxed as separate entities at a flat rate of 30% plus applicable surcharge and cess. Additionally, partners can claim salary and interest on capital as deductible expenses, potentially reducing the overall tax burden on the firm."
//         ]
//       },
//       {
//         heading: "Required Documents for Partnership Registration",
//         content: "To register a partnership firm with the Registrar of Firms, certain documents must be prepared and submitted along with the application.",
//         points: [
//           "Partnership Deed on Appropriate Stamp Paper: The partnership deed is the foundational document that outlines all terms of the partnership. It must be executed on non-judicial stamp paper of appropriate value as per the state stamp duty regulations. The deed should clearly specify the firm name, business nature, capital contributions, profit-sharing ratios, and other essential terms.",
//           "PAN Card and Aadhaar Card of All Partners: Valid PAN cards of all partners are mandatory for obtaining the firm's PAN. Aadhaar cards are required for identity verification and may be needed for various registrations and licenses. Both documents should be self-attested copies.",
//           "Address Proof of All Partners: Partners must provide address proof such as passport, voter ID card, driver's license, or recent utility bills. These documents establish the residential address of each partner and are necessary for maintaining the firm's records.",
//           "Proof of Principal Place of Business: Documentation proving the business premises is essential. This can include a rental agreement with rent receipts and NOC from the landlord, property ownership documents, or utility bills in the firm's name. The address proof should not be older than two months.",
//           "Passport Size Photographs: Recent passport-size photographs of all partners are required for the registration application and various other registrations. These photographs should meet standard specifications and be taken against a light-colored background."
//         ]
//       },
//       {
//         heading: "Benefits of Partnership Firm",
//         content: "Choosing a partnership structure offers multiple advantages for entrepreneurs who want to collaborate and build a business together.",
//         points: [
//           "Easy to Form and Dissolve: Partnership firms can be formed with minimal formalities and documentation. Similarly, dissolution is relatively straightforward compared to companies, though it requires settlement of accounts, payment of liabilities, and distribution of remaining assets among partners.",
//           "Shared Risks and Responsibilities: Business risks are distributed among partners according to their profit-sharing ratios or as agreed in the partnership deed. This risk-sharing mechanism reduces individual exposure to business failures and provides emotional and financial support during challenging times.",
//           "Greater Access to Capital and Credit: With multiple partners contributing capital, partnership firms have access to more funds than sole proprietorships. Additionally, the combined creditworthiness of partners may help secure better financing terms from banks and financial institutions.",
//           "Flexibility in Business Operations: Partnerships are not subject to extensive regulatory requirements like companies. Partners have the freedom to modify their business structure, profit-sharing arrangements, and operational processes by mutual consent without needing government approvals.",
//           "Tax Benefits and Deductions: Partnership firms can claim various deductions including interest on partner capital, remuneration to working partners (subject to limits), and other business expenses. These deductions help reduce the taxable income of the firm and overall tax liability."
//         ]
//       }
//     ],
//     author: {
//       name: "SANTOSH KUMARI M",
//       role: "Business Advisor",
//       image: "/author-avatar.jpg",
//       updatedDate: "Oct 27, 2025"
//     }
//   }
// };

// interface DynamicTabContentProps {
//   tabName: string;
// }

// export default function DynamicTabContent({ tabName }: DynamicTabContentProps) {
//   const data = tabsData[tabName as keyof typeof tabsData];

//   if (!data) {
//     return (
//       <div className="bg-red-50 border border-red-200 rounded-lg p-6 text-center">
//         <p className="text-red-600 font-medium">
//           No data found for "{tabName}". Please check the tab name.
//         </p>
//       </div>
//     );
//   }

//   return (
//     <div className="bg-gray-50 py-12 px-4">
//       <div className="bg-white rounded-lg shadow-sm border border-gray-200 overflow-hidden max-w-5xl mx-auto">
//       {/* Author Section */}
//       <div className="bg-gray-50 px-8 py-6 border-b border-gray-200">
//         <div className="flex items-center justify-between">
//           <div className="flex items-center gap-4">
//             <div className="w-14 h-14 bg-gradient-to-br from-blue-500 to-purple-600 rounded-full flex items-center justify-center text-white font-bold text-xl">
//               {data.author.name.split(' ').map(n => n[0]).join('')}
//             </div>
//             <div>
//               <h3 className="text-base font-bold text-gray-900">
//                 {data.author.name}
//               </h3>
//               <p className="text-sm text-gray-600">{data.author.role}</p>
//             </div>
//           </div>
//           <div className="text-right">
//             <p className="text-sm text-gray-500">Updated on:</p>
//             <p className="text-sm font-semibold text-gray-900">{data.author.updatedDate}</p>
//           </div>
//         </div>
//       </div>

//       {/* Main Content */}
//       <div className="px-8 py-10 space-y-8">
//         {/* Title */}
//         <h1 className="text-3xl md:text-4xl font-bold text-gray-900 leading-tight">
//           {data.title}
//         </h1>

//         {/* Description */}
//         <p className="text-gray-700 text-base leading-relaxed">
//           {data.description}
//         </p>

//         {/* Introduction */}
//         <p className="text-gray-700 text-base leading-relaxed">
//           {data.introduction}
//         </p>

//         {/* Sections */}
//         {data.sections.map((section, index) => (
//           <div key={index} className="space-y-5">
//             <h2 className="text-2xl font-bold text-gray-900 mt-8">
//               {section.heading}
//             </h2>
            
//             <p className="text-gray-700 text-base leading-relaxed">
//               {section.content}
//             </p>

//             <ul className="space-y-4 mt-4">
//               {section.points.map((point, pointIndex) => {
//                 const [title, ...description] = point.split(':');
//                 return (
//                   <li key={pointIndex} className="flex items-start gap-3">
//                     <svg
//                       className="w-5 h-5 text-blue-600 flex-shrink-0 mt-1"
//                       fill="currentColor"
//                       viewBox="0 0 20 20"
//                     >
//                       <path
//                         fillRule="evenodd"
//                         d="M16.707 5.293a1 1 0 010 1.414l-8 8a1 1 0 01-1.414 0l-4-4a1 1 0 011.414-1.414L8 12.586l7.293-7.293a1 1 0 011.414 0z"
//                         clipRule="evenodd"
//                       />
//                     </svg>
//                     <div className="flex-1">
//                       <span className="font-semibold text-gray-900">{title}:</span>
//                       <span className="text-gray-700"> {description.join(':')}</span>
//                     </div>
//                   </li>
//                 );
//               })}
//             </ul>
//           </div>
//         ))}
//       </div>
//     </div>
//     </div>
//   );
// }

// // Example Usage Component
// export function TabsExample() {
//   const [activeTab, setActiveTab] = useState("Proprietorship");

//   const tabs = [
//     "Proprietorship",
//     "Partnership",
//     "One Person Company",
//     "Limited Liability Partnership",
//     "Private Limited Company",
//     "Section 8 Company",
//     "Trust Registration",
//     "Public Limited Company",
//     "Producer Company",
//     "Indian Subsidiary"
//   ];

//   return (
//     <div className="bg-gray-50 min-h-screen py-12 px-4">
//       <div className="max-w-7xl mx-auto space-y-6">
//       {/* Tabs Navigation */}
//       <div className="bg-white rounded-xl shadow-md border border-gray-200 p-4">
//         <div className="grid grid-cols-2 md:grid-cols-5 gap-3">
//           {tabs.map((tab) => (
//             <button
//               key={tab}
//               onClick={() => setActiveTab(tab)}
//               className={`px-4 py-3 rounded-lg text-sm font-medium transition-all ${
//                 activeTab === tab
//                   ? "bg-blue-600 text-white shadow-md"
//                   : "bg-gray-50 text-gray-700 hover:bg-gray-100 border border-gray-200"
//               }`}
//             >
//               {tab}
//             </button>
//           ))}
//         </div>
//       </div>

//       {/* Dynamic Content */}
//       <DynamicTabContent tabName={activeTab} />
//     </div>
//     </div>
//   );
// }






// interface DynamicTabContentProps {
//   tabName: string;
// }

// async function getTabData(tabName: string) {
//   const res = await fetch(
//     `http://localhost:1337/api/dynamic-tab-contents?filters[category][$eq]=${tabName}`,
//     { cache: "no-store" }
//   );

//   const json = await res.json();

//   // SAFETY CHECK
//   if (!Array.isArray(json.data) || json.data.length === 0) {
//     return null;
//   }

//   // JSON field directly
//   return json.data[0].content;
// }

// export default async function DynamicTabContent({
//   tabName,
// }: DynamicTabContentProps) {
//   const data = await getTabData(tabName);

//   if (!data) {
//     return (
//       <div className="bg-red-50 border border-red-200 rounded-lg p-6 text-center">
//         <p className="text-red-600 font-medium">
//           No data found for "{tabName}". Please check the tab name.
//         </p>
//       </div>
//     );
//   }

//   return (
//     <div className="bg-gray-50 py-12 px-4">
//       <div className="max-w-7xl mx-auto flex gap-6">
//         {/* ================= MAIN CONTENT ================= */}
//         <div className="bg-white rounded-lg shadow-sm border border-gray-200 overflow-hidden flex-1">
          
//           {/* Author Section */}
//           <div className="bg-gray-50 px-8 py-6 border-b border-gray-200">
//             <div className="flex items-center justify-between">
//               <div className="flex items-center gap-4">
//                 <div className="w-14 h-14 bg-gradient-to-br from-blue-500 to-purple-600 rounded-full flex items-center justify-center text-white font-bold text-xl">
//                   {data.author.name
//                     .split(" ")
//                     .map((n: string) => n[0])
//                     .join("")}
//                 </div>
//                 <div>
//                   <h3 className="text-base font-bold text-gray-900">
//                     {data.author.name}
//                   </h3>
//                   <p className="text-sm text-gray-600">
//                     {data.author.role}
//                   </p>
//                 </div>
//               </div>
//               <div className="text-right">
//                 <p className="text-sm text-gray-500">Updated on:</p>
//                 <p className="text-sm font-semibold text-gray-900">
//                   {data.author.updatedDate}
//                 </p>
//               </div>
//             </div>
//           </div>

//           {/* Main Content */}
//           <div className="px-8 py-10 space-y-8">
//             <h1 className="text-3xl md:text-4xl font-bold text-gray-900 leading-tight">
//               {data.title}
//             </h1>

//             <p className="text-gray-700 text-base leading-relaxed">
//               {data.description}
//             </p>

//             <p className="text-gray-700 text-base leading-relaxed">
//               {data.introduction}
//             </p>

//             {data.sections.map((section: any, index: number) => (
//               <div key={index} className="space-y-5">
//                 <h2 className="text-2xl font-bold text-gray-900 mt-8">
//                   {section.heading}
//                 </h2>

//                 <p className="text-gray-700 text-base leading-relaxed">
//                   {section.content}
//                 </p>

//                 <ul className="space-y-4 mt-4">
//                   {section.points.map(
//                     (point: string, pointIndex: number) => {
//                       const [title, ...desc] = point.split(":");
//                       return (
//                         <li
//                           key={pointIndex}
//                           className="flex items-start gap-3"
//                         >
//                           <svg
//                             className="w-5 h-5 text-blue-600 flex-shrink-0 mt-1"
//                             fill="currentColor"
//                             viewBox="0 0 20 20"
//                           >
//                             <path
//                               fillRule="evenodd"
//                               d="M16.707 5.293a1 1 0 010 1.414l-8 8a1 1 0 01-1.414 0l-4-4a1 1 0 011.414-1.414L8 12.586l7.293-7.293a1 1 0 011.414 0z"
//                               clipRule="evenodd"
//                             />
//                           </svg>
//                           <div className="flex-1">
//                             <span className="font-semibold text-gray-900">
//                               {title}:
//                             </span>
//                             <span className="text-gray-700">
//                               {" "}
//                               {desc.join(":")}
//                             </span>
//                           </div>
//                         </li>
//                       );
//                     }
//                   )}
//                 </ul>
//               </div>
//             ))}
//           </div>
//         </div>

//         {/* ================= SIDEBAR (UNCHANGED) ================= */}
//         <div className="w-80 space-y-6 flex-shrink-0 sticky top-6 self-start">
          
//           <div className="bg-white rounded-lg shadow-sm border border-gray-200 p-6">
//             <h3 className="text-lg font-bold text-gray-900 mb-4">
//               Consult Experts
//             </h3>
//             <p className="text-sm text-gray-600 mb-4">
//               Get professional guidance from our experienced consultants
//             </p>
//             <button className="w-full bg-blue-600 hover:bg-blue-700 text-white font-semibold py-2 px-4 rounded-lg transition-colors">
//               Contact Now
//             </button>
//           </div>

//           <div className="bg-white rounded-lg shadow-sm border border-gray-200 p-6">
//             <h3 className="text-lg font-bold text-gray-900 mb-4">
//               Related Guides
//             </h3>
//             <ul className="space-y-3">
//               <li className="text-sm text-blue-600 hover:underline">
//                 Online EPF account transfer
//               </li>
//               <li className="text-sm text-blue-600 hover:underline">
//                 IEPF Rules 2019
//               </li>
//               <li className="text-sm text-blue-600 hover:underline">
//                 PF Balance Check
//               </li>
//             </ul>
//           </div>
//         </div>
//       </div>
//     </div>
//   );
// }








// interface DynamicTabContentProps {
//   category: string;
// }

// async function getTabData(category: string) {
//   const res = await fetch(
//     `http://localhost:1337/api/dynamic-tab-contents?filters[category][$eq]=${category}`,
//     { cache: "no-store" }
//   );

//   const json = await res.json();

//   if (!Array.isArray(json.data) || json.data.length === 0) {
//     return null;
//   }

//   // assuming `content` is a JSON field in Strapi
//   return json.data[0].content;
// }

// export default async function DynamicTabContent({
//   category,
// }: DynamicTabContentProps) {
//   const data = await getTabData(category);

//   if (!data) {
//     return (
//       <div className="bg-red-50 border border-red-200 rounded-lg p-6 text-center">
//         <p className="text-red-600 font-medium">
//           No data found for "{category}". Please check the category.
//         </p>
//       </div>
//     );
//   }

//   /* ====== BELOW JSX IS 100% SAME AS YOUR CODE ====== */
//   return (
//     <div className="bg-gray-50 py-12 px-4">
//       <div className="max-w-7xl mx-auto flex gap-6">
//         {/* Main Content */}
//         <div className="bg-white rounded-lg shadow-sm border border-gray-200 overflow-hidden flex-1">
          
//           {/* Author Section */}
//           <div className="bg-gray-50 px-8 py-6 border-b border-gray-200">
//             <div className="flex items-center justify-between">
//               <div className="flex items-center gap-4">
//                 <div className="w-14 h-14 bg-gradient-to-br from-blue-500 to-purple-600 rounded-full flex items-center justify-center text-white font-bold text-xl">
//                   {data.author.name.split(" ").map((n: string) => n[0]).join("")}
//                 </div>
//                 <div>
//                   <h3 className="text-base font-bold text-gray-900">
//                     {data.author.name}
//                   </h3>
//                   <p className="text-sm text-gray-600">{data.author.role}</p>
//                 </div>
//               </div>
//               <div className="text-right">
//                 <p className="text-sm text-gray-500">Updated on:</p>
//                 <p className="text-sm font-semibold text-gray-900">
//                   {data.author.updatedDate}
//                 </p>
//               </div>
//             </div>
//           </div>

//           {/* Main Content */}
//           <div className="px-8 py-10 space-y-8">
//             <h1 className="text-3xl md:text-4xl font-bold text-gray-900 leading-tight">
//               {data.title}
//             </h1>

//             <p className="text-gray-700 text-base leading-relaxed">
//               {data.description}
//             </p>

//             <p className="text-gray-700 text-base leading-relaxed">
//               {data.introduction}
//             </p>

//             {data.sections.map((section: any, index: number) => (
//               <div key={index} className="space-y-5">
//                 <h2 className="text-2xl font-bold text-gray-900 mt-8">
//                   {section.heading}
//                 </h2>

//                 <p className="text-gray-700 text-base leading-relaxed">
//                   {section.content}
//                 </p>

//                 <ul className="space-y-4 mt-4">
//                   {section.points.map((point: string, i: number) => {
//                     const [title, ...desc] = point.split(":");
//                     return (
//                       <li key={i} className="flex items-start gap-3">
//                         <svg
//                           className="w-5 h-5 text-blue-600 flex-shrink-0 mt-1"
//                           fill="currentColor"
//                           viewBox="0 0 20 20"
//                         >
//                           <path
//                             fillRule="evenodd"
//                             d="M16.707 5.293a1 1 0 010 1.414l-8 8a1 1 0 01-1.414 0l-4-4a1 1 0 011.414-1.414L8 12.586l7.293-7.293a1 1 0 011.414 0z"
//                             clipRule="evenodd"
//                           />
//                         </svg>
//                         <div>
//                           <span className="font-semibold text-gray-900">
//                             {title}:
//                           </span>
//                           <span className="text-gray-700">
//                             {" "}
//                             {desc.join(":")}
//                           </span>
//                         </div>
//                       </li>
//                     );
//                   })}
//                 </ul>
//               </div>
//             ))}
//           </div>
//         </div>

//         {/* Sidebar — unchanged */}
//         {/* Sidebar */}
//         <div className="w-80 space-y-6 flex-shrink-0 sticky top-6 self-start">
//           {/* Consult Experts */}
//           <div className="bg-white rounded-lg shadow-sm border border-gray-200 p-6">
//             <h3 className="text-lg font-bold text-gray-900 mb-4">Consult Experts</h3>
//             <div className="flex items-center gap-3 mb-4">
//               <div className="flex -space-x-2">
//                 <div className="w-10 h-10 rounded-full bg-gradient-to-br from-blue-400 to-blue-600 border-2 border-white"></div>
//                 <div className="w-10 h-10 rounded-full bg-gradient-to-br from-purple-400 to-purple-600 border-2 border-white"></div>
//                 <div className="w-10 h-10 rounded-full bg-gradient-to-br from-pink-400 to-pink-600 border-2 border-white"></div>
//               </div>
//               <span className="text-sm font-semibold text-gray-700">Expert Team</span>
//             </div>
//             <p className="text-sm text-gray-600 mb-4">
//               Get professional guidance from our experienced consultants
//             </p>
//             <button className="w-full bg-blue-600 hover:bg-blue-700 text-white font-semibold py-2 px-4 rounded-lg transition-colors">
//               Contact Now
//             </button>
//           </div>

//           {/* Related Guides */}
//           <div className="bg-white rounded-lg shadow-sm border border-gray-200 p-6">
//             <h3 className="text-lg font-bold text-gray-900 mb-4">Related Guides</h3>
//             <ul className="space-y-3">
//               <li>
//                 <a href="#" className="text-sm text-blue-600 hover:text-blue-800 hover:underline">
//                   Online EPF account transfer
//                 </a>
//               </li>
//               <li>
//                 <a href="#" className="text-sm text-blue-600 hover:text-blue-800 hover:underline">
//                   IEPF Rules 2019 – Investor Education and Protection Fund
//                 </a>
//               </li>
//               <li>
//                 <a href="#" className="text-sm text-blue-600 hover:text-blue-800 hover:underline">
//                   Reduced Rate Of EPF Contribution & Impact On Stakeholders
//                 </a>
//               </li>
//               <li>
//                 <a href="#" className="text-sm text-blue-600 hover:text-blue-800 hover:underline">
//                   PF Balance Check
//                 </a>
//               </li>
//             </ul>
//           </div>
//         </div>
//       </div>
//     </div>
//   );
// }



// cockpit from here
"use client";

import { useEffect, useState } from "react";

interface DynamicTabContentProps {
  category: string;
}

const TOKEN = "API-d969d00908e5d49261dc97c71fdd75794712b377";

const API =
  `https://cms.dostartup.in/api/content/items/dynamicTabContent?token=${TOKEN}`;

export default function DynamicTabContent({ category }: DynamicTabContentProps) {
  const [data, setData] = useState<any>(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    async function fetchData() {
      try {
        const res = await fetch(API);
        const json = await res.json();

        // Cockpit returns array directly
        if (Array.isArray(json)) {
          const matched = json.find(
            (item: any) =>
              item.category === category ||
              item.CATEGORY === category
          );

          setData(matched?.content || matched || null);
        }
      } catch (err) {
        console.error("Cockpit fetch error:", err);
      } finally {
        setLoading(false);
      }
    }

    fetchData();
  }, [category]);

  if (loading) {
    return (
      <div className="p-10 text-center text-gray-500">
        Loading content...
      </div>
    );
  }

  if (!data) {
    return (
      <div className="bg-red-50 border border-red-200 rounded-lg p-6 text-center">
        <p className="text-red-600 font-medium">
          No data found for "{category}". Please check the category.
        </p>
      </div>
    );
  }

  return (
    <div className="bg-gray-50 py-12 px-4">
      <div className="max-w-7xl mx-auto flex gap-6">

        {/* Main Content */}
        <div className="bg-white rounded-lg shadow-sm border border-gray-200 overflow-hidden flex-1">

          {/* Author */}
          <div className="bg-gray-50 px-8 py-6 border-b border-gray-200">
            <div className="flex items-center justify-between">

              <div className="flex items-center gap-4">
                <div className="w-14 h-14 bg-gradient-to-br from-blue-500 to-purple-600 rounded-full flex items-center justify-center text-white font-bold text-xl">
                  {data.author?.name
                    ?.split(" ")
                    .map((n: string) => n[0])
                    .join("")}
                </div>

                <div>
                  <h3 className="text-base font-bold text-gray-900">
                    {data.author?.name}
                  </h3>
                  <p className="text-sm text-gray-600">
                    {data.author?.role}
                  </p>
                </div>
              </div>

              <div className="text-right">
                <p className="text-sm text-gray-500">Updated on:</p>
                <p className="text-sm font-semibold text-gray-900">
                  {data.author?.updatedDate}
                </p>
              </div>

            </div>
          </div>

          {/* Body */}
          <div className="px-8 py-10 space-y-8">

            <h1 className="text-3xl md:text-4xl font-bold text-gray-900">
              {data.title}
            </h1>

            <p className="text-gray-700">{data.description}</p>
            <p className="text-gray-700">{data.introduction}</p>

            {data.sections?.map((section: any, index: number) => (
              <div key={index} className="space-y-5">

                <h2 className="text-2xl font-bold text-gray-900 mt-8">
                  {section.heading}
                </h2>

                <p className="text-gray-700">{section.content}</p>

                <ul className="space-y-4 mt-4">
                  {section.points?.map((point: string, i: number) => {
                    const [title, ...desc] = point.split(":");

                    return (
                      <li key={i} className="flex items-start gap-3">
                        <svg
                          className="w-5 h-5 text-blue-600 mt-1"
                          fill="currentColor"
                          viewBox="0 0 20 20"
                        >
                          <path
                            fillRule="evenodd"
                            d="M16.707 5.293a1 1 0 010 1.414l-8 8a1 1 0 01-1.414 0l-4-4a1 1 0 011.414-1.414L8 12.586l7.293-7.293a1 1 0 011.414 0z"
                            clipRule="evenodd"
                          />
                        </svg>

                        <div>
                          <span className="font-semibold text-gray-900">
                            {title}:
                          </span>
                          <span className="text-gray-700">
                            {" "}{desc.join(":")}
                          </span>
                        </div>

                      </li>
                    );
                  })}
                </ul>

              </div>
            ))}

          </div>
        </div>

        {/* Sidebar unchanged */}
        <div className="w-80 space-y-6 flex-shrink-0 sticky top-6 self-start">

          <div className="bg-white rounded-lg shadow-sm border border-gray-200 p-6">
            <h3 className="text-lg font-bold text-gray-900 mb-4">
              Consult Experts
            </h3>

            <p className="text-sm text-gray-600 mb-4">
              Get professional guidance from our experienced consultants
            </p>

            <button className="w-full bg-blue-600 hover:bg-blue-700 text-white font-semibold py-2 px-4 rounded-lg">
              Contact Now
            </button>
          </div>

        </div>

      </div>
    </div>
  );
}
